/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.regex.*;
import javax.swing.RowFilter;


/**
 *
 * @author HP
 */
public class Admin1 extends javax.swing.JFrame {

    /**
     * Creates new form Admin1
     */
    public Admin1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        firstpage2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tfname2 = new javax.swing.JTextField();
        tfadd2 = new javax.swing.JTextField();
        tfpin2 = new javax.swing.JTextField();
        tfphoneno2 = new javax.swing.JTextField();
        CREATEBUTTON2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jComboBoxDepartment1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        tfdoctorid = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBoxexperience = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        tfsearch3 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        UPDATEB2 = new javax.swing.JButton();
        LOGOUTB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        firstpage1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfname1 = new javax.swing.JTextField();
        tfadd1 = new javax.swing.JTextField();
        tfpin1 = new javax.swing.JTextField();
        tfphoneno1 = new javax.swing.JTextField();
        MaleRadioButton2 = new javax.swing.JRadioButton();
        femaleRadioButton1 = new javax.swing.JRadioButton();
        CREATEBUTTON1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tfbodytemp = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfbloodpressure = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfage1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfrespirationrate = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfencounterdate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        tfsearch2 = new javax.swing.JTextField();
        UPDATEB1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        firstpage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfadd = new javax.swing.JTextField();
        tfpin = new javax.swing.JTextField();
        tfphoneno = new javax.swing.JTextField();
        MaleRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        CREATEBUTTON = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfbloodgp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDepartment = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfage = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfwardno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfsearch1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfsearch = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Updateb = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        firstpage2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel29.setText("NAME");

        jLabel30.setText("PINCODE");

        jLabel31.setText("ADDRESS");

        jLabel32.setText("CITY");

        CREATEBUTTON2.setText("CREATE");
        CREATEBUTTON2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBUTTON2ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel34.setText("ENTER DOCTOR DETAILS");

        jLabel35.setText("DEPARTMENT");

        jComboBoxDepartment1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "DENTAL", "MICROBIOLOGY", "CARDIOLOGY", "GYNAECOLOGY", "NEUROLOGY", " " }));

        jLabel36.setText("DOCTOR ID");

        jLabel37.setText("EXPERIENCE");

        jComboBoxexperience.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "0-5", "5-10", "10-15", "15-25", "25-35" }));
        jComboBoxexperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxexperienceActionPerformed(evt);
            }
        });

        jTable3.setBackground(new java.awt.Color(204, 255, 0));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "PINCODE", "EXPERIENCE", "CITY", "DEPARTMENT", "DOCTORID"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        tfsearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearch3ActionPerformed(evt);
            }
        });
        tfsearch3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearch3KeyReleased(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel38.setText("SEARCH");

        UPDATEB2.setText("UPDATE");
        UPDATEB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEB2ActionPerformed(evt);
            }
        });

        LOGOUTB.setText("LOGOUT");
        LOGOUTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstpage2Layout = new javax.swing.GroupLayout(firstpage2);
        firstpage2.setLayout(firstpage2Layout);
        firstpage2Layout.setHorizontalGroup(
            firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpage2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(38, 38, 38)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CREATEBUTTON2)
                            .addGroup(firstpage2Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel34)))
                        .addGap(1167, 1167, 1167))
                    .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstpage2Layout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstpage2Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(firstpage2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(tfdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBoxDepartment1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxexperience, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfpin2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfadd2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfname2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfphoneno2))
                            .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(firstpage2Layout.createSequentialGroup()
                                    .addGap(261, 261, 261)
                                    .addComponent(jLabel38)
                                    .addGap(53, 53, 53)
                                    .addComponent(tfsearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(firstpage2Layout.createSequentialGroup()
                                    .addGap(116, 116, 116)
                                    .addComponent(UPDATEB2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(139, 139, 139)
                                    .addComponent(LOGOUTB)))
                            .addGap(743, 743, 743)))))
            .addGroup(firstpage2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        firstpage2Layout.setVerticalGroup(
            firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstpage2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel34)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(tfname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsearch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel30))
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addComponent(tfadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfpin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jComboBoxexperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfphoneno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel33))
                    .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UPDATEB2)
                        .addComponent(LOGOUTB)))
                .addGap(21, 21, 21)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jComboBoxDepartment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tfdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CREATEBUTTON2)
                .addGap(341, 341, 341))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(firstpage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstpage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HOSPITALADMIN", jPanel1);

        firstpage1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel10.setText("NAME");

        jLabel12.setText("PINCODE");

        jLabel13.setText("ADDRESS");

        jLabel18.setText("GENDER");

        jLabel19.setText("PHONENO");

        tfpin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfpin1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpin1KeyTyped(evt);
            }
        });

        tfphoneno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfphoneno1ActionPerformed(evt);
            }
        });
        tfphoneno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfphoneno1KeyPressed(evt);
            }
        });

        MaleRadioButton2.setText("Male");
        MaleRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButton2ActionPerformed(evt);
            }
        });

        femaleRadioButton1.setText("FEMALE");
        femaleRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButton1ActionPerformed(evt);
            }
        });

        CREATEBUTTON1.setText("CREATE");
        CREATEBUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBUTTON1ActionPerformed(evt);
            }
        });

        jLabel21.setText("BODYTEMPERATURE");

        jLabel22.setText("SYMPTOMS");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "FEVER", "COLD", "HEADACHE", "BODYACHE", "ACNE", "DIARREHA" }));

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel23.setText("ENTER PATIENTS DETAILS");

        jLabel24.setText("BLOOD PRESSURE");

        jLabel25.setText("AGE");

        tfage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfage1ActionPerformed(evt);
            }
        });

        jLabel26.setText("RESPIRATIONRATE");

        jLabel27.setText("ENCOUNTER DATE");

        jTable2.setBackground(new java.awt.Color(255, 51, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "PINCODE", "GENDER", "PHONENO", "BODYTEMP", "SYMPTOMS", "BP", "AGE", "RESPIRATIONRATE", "ENCOUNTER DATE"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel28.setText("SEARCH");

        tfsearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearch2ActionPerformed(evt);
            }
        });
        tfsearch2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearch2KeyReleased(evt);
            }
        });

        UPDATEB1.setText("UPDATE");
        UPDATEB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstpage1Layout = new javax.swing.GroupLayout(firstpage1);
        firstpage1.setLayout(firstpage1Layout);
        firstpage1Layout.setHorizontalGroup(
            firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpage1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(firstpage1Layout.createSequentialGroup()
                            .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(99, 99, 99)
                            .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(firstpage1Layout.createSequentialGroup()
                                    .addComponent(MaleRadioButton2)
                                    .addGap(31, 31, 31)
                                    .addComponent(femaleRadioButton1))
                                .addComponent(jLabel23)
                                .addComponent(tfname1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(tfadd1)
                                .addComponent(tfpin1)))
                        .addGroup(firstpage1Layout.createSequentialGroup()
                            .addComponent(CREATEBUTTON1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UPDATEB1)
                            .addGap(101, 101, 101))
                        .addGroup(firstpage1Layout.createSequentialGroup()
                            .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25))
                            .addGap(34, 34, 34)
                            .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfphoneno1)
                                .addComponent(tfbodytemp)
                                .addGroup(firstpage1Layout.createSequentialGroup()
                                    .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfage1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfbloodpressure, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 251, Short.MAX_VALUE)
                                        .addComponent(tfrespirationrate)
                                        .addComponent(tfencounterdate))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel28)
                        .addGap(46, 46, 46)
                        .addComponent(tfsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(576, Short.MAX_VALUE))
        );
        firstpage1Layout.setVerticalGroup(
            firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpage1Layout.createSequentialGroup()
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstpage1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel23))
                            .addGroup(firstpage1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel28)))
                        .addGap(17, 17, 17)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(tfsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(firstpage1Layout.createSequentialGroup()
                                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfpin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MaleRadioButton2)
                                    .addComponent(femaleRadioButton1))))
                        .addGap(18, 18, 18)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfphoneno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20)
                        .addGap(16, 16, 16)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(tfbodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(34, 34, 34)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tfbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tfage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tfrespirationrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tfencounterdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CREATEBUTTON1)
                    .addComponent(UPDATEB1))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(firstpage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(firstpage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DOCTOR", jPanel2);

        firstpage.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("NAME");

        jLabel2.setText("PINCODE");

        jLabel3.setText("ADDRESS");

        jLabel4.setText("GENDER");

        jLabel5.setText("PHONENO");

        MaleRadioButton1.setText("MALE");

        jRadioButton2.setText("FEMALE");

        CREATEBUTTON.setText("BOOK APOINTMENT");
        CREATEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBUTTONActionPerformed(evt);
            }
        });

        jLabel8.setText("DEPARTMENT");

        jComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "DENTAL", "MICROBIOLOGY", "CARDIOLOGY", "GYNAECOLOGY", "NEUROLOGY", " " }));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("BOOK APPOINTMENT");

        jLabel11.setText("AGE");

        tfage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfageActionPerformed(evt);
            }
        });

        jLabel15.setText("WARDNO");

        tfwardno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfwardnoActionPerformed(evt);
            }
        });

        jLabel16.setText("BLOODGROUP");

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setText("SEARCH DOCTOR");

        tfsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearch1ActionPerformed(evt);
            }
        });
        tfsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearch1KeyReleased(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 51, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "PINCODE", "GENDER", "PHONENO", "BLOODGROUP", "DEPARTMENT", "AGE", "WARDNO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearchKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setText("SEARCH BOOKING DETAILS");

        Updateb.setText("UPDATE");
        Updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstpageLayout = new javax.swing.GroupLayout(firstpage);
        firstpage.setLayout(firstpageLayout);
        firstpageLayout.setHorizontalGroup(
            firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpageLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(99, 99, 99)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfphoneno)
                            .addGroup(firstpageLayout.createSequentialGroup()
                                .addComponent(MaleRadioButton1)
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButton2))
                            .addComponent(jLabel9)
                            .addComponent(tfname)
                            .addComponent(tfadd)
                            .addComponent(tfpin)))
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(71, 71, 71)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfage, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.Alignment.LEADING, 0, 189, Short.MAX_VALUE)
                            .addComponent(tfwardno)
                            .addGroup(firstpageLayout.createSequentialGroup()
                                .addComponent(tfbloodgp)
                                .addGap(6, 6, 6))))
                    .addComponent(CREATEBUTTON))
                .addGap(104, 104, 104)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(646, Short.MAX_VALUE))
        );
        firstpageLayout.setVerticalGroup(
            firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpageLayout.createSequentialGroup()
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9))
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tfsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14)
                            .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaleRadioButton1)
                            .addComponent(jRadioButton2))))
                .addGap(18, 18, 18)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(16, 16, 16)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfbloodgp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(32, 32, 32)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfwardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(Updateb)
                .addGap(24, 24, 24)
                .addComponent(CREATEBUTTON)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(firstpage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(firstpage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 287, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PATIENT", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1701, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("COMMUNITY", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1701, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel5);

        getContentPane().add(jTabbedPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CREATEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBUTTONActionPerformed
        if(tfname.getText().equals("")||tfadd.getText().equals("")||tfpin.getText().equals("")||tfphoneno.getText().equals("")||tfbloodgp.getText().equals("")||tfage.getText().equals("")||tfwardno.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter All Details");
        }
             else
       {
           String data[]={tfname.getText(),tfadd.getText(),tfpin.getText(),MaleRadioButton1.getText(),tfphoneno.getText(),tfbloodgp.getText(),jComboBoxDepartment.getSelectedItem().toString(),tfage.getText(),tfwardno.getText()};
              DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                tb1Model.addRow(data); 
                JOptionPane.showMessageDialog(this,"Appointment Booked  Successfully!");
                tfname.setText("");
                tfadd.setText("");
                tfpin.setText("");
                tfphoneno.setText("");
                tfbloodgp.setText("");
                jComboBoxDepartment.setSelectedItem("");
                tfage.setText("");
                tfwardno.setText("");
       }
    }//GEN-LAST:event_CREATEBUTTONActionPerformed

    private void tfageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfageActionPerformed

    private void tfwardnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfwardnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfwardnoActionPerformed

    private void tfsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsearch1ActionPerformed

    private void tfsearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearch1KeyReleased
      
    }//GEN-LAST:event_tfsearch1KeyReleased

    private void tfsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearchKeyReleased
        DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
        jTable1.getModel();
        TableRowSorter <DefaultTableModel> tb = new TableRowSorter <DefaultTableModel>(tableModel);
        jTable1.setRowSorter(tb);
        tb.setRowFilter(RowFilter.regexFilter(tfsearch.getText()));
    }//GEN-LAST:event_tfsearchKeyReleased

    private void UpdatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1)
        {
            String name=tfname.getText();
            String address=tfadd.getText();
            String pincode=tfpin.getText();
            String phno=tfphoneno.getText();
            String bt=tfbloodgp.getText();
            String age=tfage.getText();
            String wardno=tfwardno.getText();
            JOptionPane.showMessageDialog(this,"Updated Successfully");
        }
        else{
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                JOptionPane.showMessageDialog(this,"Please select a single row for updation");
            }
        }
    }//GEN-LAST:event_UpdatebActionPerformed

    private void tfpin1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpin1KeyPressed

    }//GEN-LAST:event_tfpin1KeyPressed

    private void tfpin1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpin1KeyTyped
        char c= evt.getKeyChar();
        if(!(Character.isDigit(c)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfpin1KeyTyped

    private void tfphoneno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfphoneno1ActionPerformed

    }//GEN-LAST:event_tfphoneno1ActionPerformed

    private void tfphoneno1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfphoneno1KeyPressed
        String MOB = tfphoneno.getText();
        if(MOB.matches("^[1-9]{1}[0-9]{9}$") ){
            tfphoneno.setBackground(java.awt.Color.green);
            tfphoneno.setEditable(true);
        }
        else{
            tfphoneno.setBackground(java.awt.Color.red);

        }
    }//GEN-LAST:event_tfphoneno1KeyPressed

    private void MaleRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButton2ActionPerformed

        String Gender;
        Gender="MALE";
    }//GEN-LAST:event_MaleRadioButton2ActionPerformed

    private void femaleRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButton1ActionPerformed
        String Gender;
        Gender="FEMALE";
    }//GEN-LAST:event_femaleRadioButton1ActionPerformed

    private void CREATEBUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBUTTON1ActionPerformed
        if(tfname1.getText().equals("")||tfadd1.getText().equals("")||tfpin1.getText().equals("")||tfphoneno1.getText().equals("")||tfbodytemp.getText().equals("")||tfbloodpressure.getText().equals("")||jComboBox1. getSelectedItem().equals("")||tfage1.getText().equals("")||tfrespirationrate.getText().equals("")||tfencounterdate.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter All Details");
        }
        else
       {
           
           String data[]={tfname1.getText(),tfadd1.getText(),tfpin1.getText(),MaleRadioButton2.getText(),tfphoneno1.getText(),tfbodytemp.getText(),jComboBox1.getSelectedItem().toString(),tfbloodpressure.getText(),tfage1.getText(),tfrespirationrate.getText(),tfencounterdate.getText()};
             DefaultTableModel tb1Model=(DefaultTableModel)jTable2.getModel();
                tb1Model.addRow(data);
                JOptionPane.showMessageDialog(this,"Add Data Successfully!");
                tfname1.setText("");
                tfadd1.setText("");
                tfpin1.setText("");
                tfphoneno1.setText("");
                tfbodytemp.setText("");
                jComboBox1. setSelectedItem("");
                tfbloodpressure.setText("");
                tfage1.setText("");
                tfrespirationrate.setText("");
                tfencounterdate.setText("");
                         
    }
            
    }//GEN-LAST:event_CREATEBUTTON1ActionPerformed

    private void tfage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfage1ActionPerformed

    private void tfsearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsearch2ActionPerformed

    private void tfsearch2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearch2KeyReleased
        DefaultTableModel tableModel = (DefaultTableModel)jTable2.getModel();
        jTable2.getModel();
        TableRowSorter <DefaultTableModel> tb = new TableRowSorter <DefaultTableModel>(tableModel);
        jTable2.setRowSorter(tb);
        tb.setRowFilter(RowFilter.regexFilter(tfsearch2.getText()));
    }//GEN-LAST:event_tfsearch2KeyReleased

    private void UPDATEB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEB1ActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)jTable2.getModel();
        if(jTable2.getSelectedRowCount()==1)
        {
            String name=tfname1.getText();
            String address=tfadd1.getText();
            String pincode=tfpin1.getText();
            String phno=tfphoneno1.getText();
            String bt=tfbodytemp.getText();
            String bp=tfbloodpressure.getText();
            String age=tfage1.getText();
            String RespirationRate=tfrespirationrate.getText();
            JOptionPane.showMessageDialog(this,"Updated Successfully");
        }
        else{
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                JOptionPane.showMessageDialog(this,"Please select a single row for updation");
            }
        }
    }//GEN-LAST:event_UPDATEB1ActionPerformed

    private void CREATEBUTTON2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBUTTON2ActionPerformed
        if(tfname2.getText().equals("")||tfadd2.getText().equals("")||tfpin2.getText().equals("")||jComboBoxexperience. getSelectedItem().equals("")||tfphoneno2.getText().equals("")||jComboBoxDepartment1. getSelectedItem().equals("")||tfdoctorid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter All Details");
        }
        else
       {
           String data[]={tfname2.getText(),tfadd2.getText(),tfpin2.getText(), jComboBoxexperience.getSelectedItem().toString(),tfphoneno2.getText(),jComboBoxDepartment1.getSelectedItem().toString(),tfdoctorid.getText()};
              DefaultTableModel tb1Model=(DefaultTableModel)jTable3.getModel();
                tb1Model.addRow(data); 
                JOptionPane.showMessageDialog(this,"Add Data Successfully!");
                tfname2.setText("");
                tfadd2.setText("");
                tfpin2.setText("");
                tfphoneno2.setText("");
                tfdoctorid.setText("");
                 jComboBoxDepartment1. setSelectedItem("");
                  jComboBoxexperience. setSelectedItem("");
                
       }
    }//GEN-LAST:event_CREATEBUTTON2ActionPerformed

    private void jComboBoxexperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxexperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxexperienceActionPerformed

    private void tfsearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsearch3ActionPerformed

    private void tfsearch3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearch3KeyReleased
        DefaultTableModel tableModel = (DefaultTableModel)jTable3.getModel();
        jTable3.getModel();
        TableRowSorter <DefaultTableModel> tb = new TableRowSorter <DefaultTableModel>(tableModel);
        jTable3.setRowSorter(tb);
        tb.setRowFilter(RowFilter.regexFilter(tfsearch3.getText()));
    }//GEN-LAST:event_tfsearch3KeyReleased

    private void UPDATEB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEB2ActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1)
        {
            String name=tfname1.getText();
            String address=tfadd1.getText();
            String pincode=tfpin1.getText();
            String phno=tfphoneno1.getText();
            String doctor=tfdoctorid.getText();

            JOptionPane.showMessageDialog(this,"Updated Successfully");
        }
        else{
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                JOptionPane.showMessageDialog(this,"Please select a single row for updation");
            }
        }
    }//GEN-LAST:event_UPDATEB2ActionPerformed

    private void LOGOUTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTBActionPerformed
        Loginpage p=new Loginpage();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUTBActionPerformed
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREATEBUTTON;
    private javax.swing.JButton CREATEBUTTON1;
    private javax.swing.JButton CREATEBUTTON2;
    private javax.swing.JButton LOGOUTB;
    private javax.swing.JRadioButton MaleRadioButton1;
    private javax.swing.JRadioButton MaleRadioButton2;
    private javax.swing.JButton UPDATEB1;
    private javax.swing.JButton UPDATEB2;
    private javax.swing.JButton Updateb;
    private javax.swing.JRadioButton femaleRadioButton1;
    private javax.swing.JPanel firstpage;
    private javax.swing.JPanel firstpage1;
    private javax.swing.JPanel firstpage2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxDepartment;
    private javax.swing.JComboBox<String> jComboBoxDepartment1;
    private javax.swing.JComboBox<String> jComboBoxexperience;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfadd1;
    private javax.swing.JTextField tfadd2;
    private javax.swing.JTextField tfage;
    private javax.swing.JTextField tfage1;
    private javax.swing.JTextField tfbloodgp;
    private javax.swing.JTextField tfbloodpressure;
    private javax.swing.JTextField tfbodytemp;
    private javax.swing.JTextField tfdoctorid;
    private javax.swing.JTextField tfencounterdate;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfname1;
    private javax.swing.JTextField tfname2;
    private javax.swing.JTextField tfphoneno;
    private javax.swing.JTextField tfphoneno1;
    private javax.swing.JTextField tfphoneno2;
    private javax.swing.JTextField tfpin;
    private javax.swing.JTextField tfpin1;
    private javax.swing.JTextField tfpin2;
    private javax.swing.JTextField tfrespirationrate;
    private javax.swing.JTextField tfsearch;
    private javax.swing.JTextField tfsearch1;
    private javax.swing.JTextField tfsearch2;
    private javax.swing.JTextField tfsearch3;
    private javax.swing.JTextField tfwardno;
    // End of variables declaration//GEN-END:variables
}
