/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class Admin1 extends javax.swing.JFrame {

    /**
     * Creates new form Admin1
     */
    public Admin1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        firstpage2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfname2 = new javax.swing.JTextField();
        tfadd2 = new javax.swing.JTextField();
        tfpin2 = new javax.swing.JTextField();
        tfphoneno2 = new javax.swing.JTextField();
        CREATEBUTTON2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBoxDepartment1 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        tfdoctorid = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jComboBoxexperience = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfsearch = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        UPDATEB1 = new javax.swing.JButton();
        LOGOUTB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        firstpage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfadd = new javax.swing.JTextField();
        tfpin = new javax.swing.JTextField();
        tfphoneno = new javax.swing.JTextField();
        MaleRadioButton1 = new javax.swing.JRadioButton();
        femaleRadioButton1 = new javax.swing.JRadioButton();
        CREATEBUTTON = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfbodytemp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfbloodpressure = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfage = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfrespirationrate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        firstpage1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfname1 = new javax.swing.JTextField();
        tfadd1 = new javax.swing.JTextField();
        tfpin1 = new javax.swing.JTextField();
        tfphoneno1 = new javax.swing.JTextField();
        MaleRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        CREATEBUTTON1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        tfbloodgp = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxDepartment = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tfage1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfwardno = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        firstpage2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel25.setText("NAME");

        jLabel26.setText("PINCODE");

        jLabel27.setText("ADDRESS");

        jLabel28.setText("PHONENO");

        CREATEBUTTON2.setText("CREATE");
        CREATEBUTTON2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBUTTON2ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel30.setText("ENTER DOCTOR DETAILS");

        jLabel31.setText("DEPARTMENT");

        jComboBoxDepartment1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "DENTAL", "MICROBIOLOGY", "CARDIOLOGY", "GYNAECOLOGY", "NEUROLOGY", " " }));

        jLabel32.setText("DOCTOR ID");

        jLabel33.setText("EXPERIENCE");

        jComboBoxexperience.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "0-5", "5-10", "10-15", "15-25", "25-35" }));
        jComboBoxexperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxexperienceActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "PINCODE", "EXPERIENCE", "PHONENUMBER", "DEPARTMENT", "DOCTORID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tfsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearchActionPerformed(evt);
            }
        });
        tfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearchKeyReleased(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel34.setText("SEARCH");

        UPDATEB1.setText("UPDATE");
        UPDATEB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEB1ActionPerformed(evt);
            }
        });

        LOGOUTB.setText("LOGOUT");
        LOGOUTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstpage2Layout = new javax.swing.GroupLayout(firstpage2);
        firstpage2.setLayout(firstpage2Layout);
        firstpage2Layout.setHorizontalGroup(
            firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpage2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(38, 38, 38)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CREATEBUTTON2)
                            .addGroup(firstpage2Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel30)))
                        .addGap(1167, 1167, 1167))
                    .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstpage2Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(firstpage2Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(firstpage2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(tfdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBoxDepartment1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxexperience, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfpin2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfadd2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfname2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfphoneno2))
                            .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(firstpage2Layout.createSequentialGroup()
                                    .addGap(261, 261, 261)
                                    .addComponent(jLabel34)
                                    .addGap(53, 53, 53)
                                    .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(firstpage2Layout.createSequentialGroup()
                                    .addGap(116, 116, 116)
                                    .addComponent(UPDATEB1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(139, 139, 139)
                                    .addComponent(LOGOUTB))
                                .addGroup(firstpage2Layout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(680, 680, 680)))))
        );
        firstpage2Layout.setVerticalGroup(
            firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstpage2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel30)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(tfname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel26))
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addComponent(tfadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfpin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33)
                    .addComponent(jComboBoxexperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstpage2Layout.createSequentialGroup()
                        .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfphoneno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29))
                    .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UPDATEB1)
                        .addComponent(LOGOUTB)))
                .addGap(21, 21, 21)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jComboBoxDepartment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(tfdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(CREATEBUTTON2)
                .addGap(341, 341, 341))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(firstpage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstpage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HOSPITALADMIN", jPanel1);

        firstpage.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setText("NAME");

        jLabel2.setText("PINCODE");

        jLabel3.setText("ADDRESS");

        jLabel4.setText("GENDER");

        jLabel5.setText("PHONENO");

        tfpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfpinKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpinKeyTyped(evt);
            }
        });

        tfphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfphonenoActionPerformed(evt);
            }
        });
        tfphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfphonenoKeyPressed(evt);
            }
        });

        MaleRadioButton1.setText("Male");
        MaleRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButton1ActionPerformed(evt);
            }
        });

        femaleRadioButton1.setText("FEMALE");
        femaleRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButton1ActionPerformed(evt);
            }
        });

        CREATEBUTTON.setText("CREATE");
        CREATEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBUTTONActionPerformed(evt);
            }
        });

        jLabel7.setText("BODYTEMPERATURE");

        jLabel8.setText("SYMPTOMS");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "FEVER", "COLD", "HEADACHE", "BODYACHE", "ACNE", "DIARREHA" }));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("ENTER PATIENTS DETAILS");

        jLabel10.setText("BLOOD PRESSURE");

        jLabel11.setText("AGE");

        tfage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfageActionPerformed(evt);
            }
        });

        jLabel15.setText("RESPIRATIONRATE");

        javax.swing.GroupLayout firstpageLayout = new javax.swing.GroupLayout(firstpage);
        firstpage.setLayout(firstpageLayout);
        firstpageLayout.setHorizontalGroup(
            firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpageLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(firstpageLayout.createSequentialGroup()
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(99, 99, 99)
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(firstpageLayout.createSequentialGroup()
                                    .addComponent(MaleRadioButton1)
                                    .addGap(31, 31, 31)
                                    .addComponent(femaleRadioButton1))
                                .addComponent(jLabel9)
                                .addComponent(tfname, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(tfadd)
                                .addComponent(tfpin)))
                        .addComponent(CREATEBUTTON)
                        .addGroup(firstpageLayout.createSequentialGroup()
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(34, 34, 34)
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfphoneno)
                                .addComponent(tfbodytemp)
                                .addGroup(firstpageLayout.createSequentialGroup()
                                    .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfage, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfbloodpressure, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 251, Short.MAX_VALUE)
                                        .addComponent(tfrespirationrate))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(1150, Short.MAX_VALUE))
        );
        firstpageLayout.setVerticalGroup(
            firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaleRadioButton1)
                            .addComponent(femaleRadioButton1))))
                .addGap(18, 18, 18)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfbodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfrespirationrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(CREATEBUTTON)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1701, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(firstpage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(firstpage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("DOCTOR", jPanel2);

        firstpage1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel12.setText("NAME");

        jLabel13.setText("PINCODE");

        jLabel14.setText("ADDRESS");

        jLabel16.setText("GENDER");

        jLabel17.setText("PHONENO");

        MaleRadioButton2.setText("MALE");

        jRadioButton2.setText("FEMALE");

        CREATEBUTTON1.setText("BOOK APOINTMENT");
        CREATEBUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBUTTON1ActionPerformed(evt);
            }
        });

        jLabel20.setText("DEPARTMENT");

        jComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "DENTAL", "MICROBIOLOGY", "CARDIOLOGY", "GYNAECOLOGY", "NEUROLOGY", " " }));

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel21.setText("BOOK APPOINTMENT");

        jLabel22.setText("AGE");

        tfage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfage1ActionPerformed(evt);
            }
        });

        jLabel23.setText("WARDNO");

        tfwardno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfwardnoActionPerformed(evt);
            }
        });

        jLabel24.setText("BLOODGROUP");

        javax.swing.GroupLayout firstpage1Layout = new javax.swing.GroupLayout(firstpage1);
        firstpage1.setLayout(firstpage1Layout);
        firstpage1Layout.setHorizontalGroup(
            firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpage1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addGap(71, 71, 71)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfage1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.Alignment.LEADING, 0, 189, Short.MAX_VALUE)
                            .addComponent(tfwardno)
                            .addGroup(firstpage1Layout.createSequentialGroup()
                                .addComponent(tfbloodgp)
                                .addGap(6, 6, 6))))
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(99, 99, 99)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfphoneno1)
                            .addGroup(firstpage1Layout.createSequentialGroup()
                                .addComponent(MaleRadioButton2)
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButton2))
                            .addComponent(jLabel21)
                            .addComponent(tfname1)
                            .addComponent(tfadd1)
                            .addComponent(tfpin1)))
                    .addComponent(CREATEBUTTON1))
                .addGap(400, 400, 400))
        );
        firstpage1Layout.setVerticalGroup(
            firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpage1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel21)
                .addGap(32, 32, 32)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(22, 22, 22)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaleRadioButton2)
                            .addComponent(jRadioButton2))))
                .addGap(18, 18, 18)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfphoneno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(10, 10, 10)
                .addComponent(jLabel18)
                .addGap(16, 16, 16)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfbloodgp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(29, 29, 29)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(30, 30, 30)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfwardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(CREATEBUTTON1)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(firstpage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 914, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(firstpage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 287, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PATIENT", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1701, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("COMMUNITY", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1701, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel5);

        getContentPane().add(jTabbedPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpinKeyPressed

    }//GEN-LAST:event_tfpinKeyPressed

    private void tfpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpinKeyTyped
        char c= evt.getKeyChar();
        if(!(Character.isDigit(c)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfpinKeyTyped

    private void tfphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfphonenoActionPerformed

    }//GEN-LAST:event_tfphonenoActionPerformed

    private void tfphonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfphonenoKeyPressed
        String MOB = tfphoneno.getText();
        if(MOB.matches("^[1-9]{1}[0-9]{9}$") ){
            tfphoneno.setBackground(java.awt.Color.green);
            tfphoneno.setEditable(true);
        }
        else{
            tfphoneno.setBackground(java.awt.Color.red);

        }
    }//GEN-LAST:event_tfphonenoKeyPressed

    private void MaleRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButton1ActionPerformed

        String Gender;
        Gender="MALE";
    }//GEN-LAST:event_MaleRadioButton1ActionPerformed

    private void femaleRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButton1ActionPerformed
        String Gender;
        Gender="FEMALE";
    }//GEN-LAST:event_femaleRadioButton1ActionPerformed

    private void CREATEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBUTTONActionPerformed
        if(tfname.getText().equals("")||tfadd.getText().equals("")||tfpin.getText().equals("")||tfphoneno.getText().equals("")||tfbodytemp.getText().equals("")||tfbloodpressure.getText().equals("")||jComboBox1. getSelectedItem().equals("")||tfage.getText().equals("")||tfrespirationrate.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter All Details");
        }
    }//GEN-LAST:event_CREATEBUTTONActionPerformed

    private void tfageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfageActionPerformed

    private void CREATEBUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBUTTON1ActionPerformed
        if(tfname.getText().equals("")||tfadd.getText().equals("")||tfpin.getText().equals("")||tfphoneno.getText().equals("")||tfbloodgp.getText().equals("")||tfage.getText().equals("")||tfwardno.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter All Details");
    }//GEN-LAST:event_CREATEBUTTON1ActionPerformed
    }
    private void tfage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfage1ActionPerformed

    private void tfwardnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfwardnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfwardnoActionPerformed

    private void CREATEBUTTON2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBUTTON2ActionPerformed
        if(tfname1.getText().equals("")||tfadd1.getText().equals("")||tfpin1.getText().equals("")||jComboBoxexperience. getSelectedItem().equals("")||tfphoneno1.getText().equals("")||jComboBoxDepartment. getSelectedItem().equals("")||tfdoctorid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter All Details");
    }//GEN-LAST:event_CREATEBUTTON2ActionPerformed
    }
    
    private void jComboBoxexperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxexperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxexperienceActionPerformed

    private void tfsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsearchActionPerformed

    private void tfsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearchKeyReleased
        DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
        jTable1.getModel();
        TableRowSorter <DefaultTableModel> tb = new TableRowSorter <DefaultTableModel>(tableModel);
        jTable1.setRowSorter(tb);
    }//GEN-LAST:event_tfsearchKeyReleased

    private void UPDATEB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEB1ActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1)
        {
            String name=tfname1.getText();
            String address=tfadd1.getText();
            String pincode=tfpin1.getText();
            String phno=tfphoneno1.getText();
            String doctor=tfdoctorid.getText();

            JOptionPane.showMessageDialog(this,"Updated Successfully");
        }
        else{
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                JOptionPane.showMessageDialog(this,"Please select a single row for updation");
            }
        }
    }//GEN-LAST:event_UPDATEB1ActionPerformed

    private void LOGOUTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTBActionPerformed
        Loginpage p=new Loginpage();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREATEBUTTON;
    private javax.swing.JButton CREATEBUTTON1;
    private javax.swing.JButton CREATEBUTTON2;
    private javax.swing.JButton LOGOUTB;
    private javax.swing.JRadioButton MaleRadioButton1;
    private javax.swing.JRadioButton MaleRadioButton2;
    private javax.swing.JButton UPDATEB1;
    private javax.swing.JRadioButton femaleRadioButton1;
    private javax.swing.JPanel firstpage;
    private javax.swing.JPanel firstpage1;
    private javax.swing.JPanel firstpage2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxDepartment;
    private javax.swing.JComboBox<String> jComboBoxDepartment1;
    private javax.swing.JComboBox<String> jComboBoxexperience;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfadd1;
    private javax.swing.JTextField tfadd2;
    private javax.swing.JTextField tfage;
    private javax.swing.JTextField tfage1;
    private javax.swing.JTextField tfbloodgp;
    private javax.swing.JTextField tfbloodpressure;
    private javax.swing.JTextField tfbodytemp;
    private javax.swing.JTextField tfdoctorid;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfname1;
    private javax.swing.JTextField tfname2;
    private javax.swing.JTextField tfphoneno;
    private javax.swing.JTextField tfphoneno1;
    private javax.swing.JTextField tfphoneno2;
    private javax.swing.JTextField tfpin;
    private javax.swing.JTextField tfpin1;
    private javax.swing.JTextField tfpin2;
    private javax.swing.JTextField tfrespirationrate;
    private javax.swing.JTextField tfsearch;
    private javax.swing.JTextField tfwardno;
    // End of variables declaration//GEN-END:variables
}
