/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import com.mycompany.hms.Doctor;
import java.util.ArrayList;
/**
 *
 * @author HP
 */
public class Doctoraccess extends javax.swing.JFrame {
   

    /**
     * Creates new form Doctoraccess
     */
    public Doctoraccess() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CREATEB = new javax.swing.JButton();
        UPDATEB = new javax.swing.JButton();
        Parent = new javax.swing.JPanel();
        firstpage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfadd = new javax.swing.JTextField();
        tfpin = new javax.swing.JTextField();
        tfphoneno = new javax.swing.JTextField();
        MaleRadioButton1 = new javax.swing.JRadioButton();
        femaleRadioButton1 = new javax.swing.JRadioButton();
        CREATEBUTTON = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfbodytemp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfbloodpressure = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfage = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfrespirationrate = new javax.swing.JTextField();
        secondpage = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfsearch = new javax.swing.JTextField();
        UPDATEB1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LOGOUTB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        CREATEB.setText("CREATE");
        CREATEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBActionPerformed(evt);
            }
        });
        jPanel1.add(CREATEB);
        CREATEB.setBounds(10, 160, 100, 22);

        UPDATEB.setText("VIEW");
        UPDATEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEBActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATEB);
        UPDATEB.setBounds(10, 250, 110, 22);

        Parent.setLayout(new java.awt.CardLayout());

        firstpage.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setText("NAME");

        jLabel2.setText("PINCODE");

        jLabel3.setText("ADDRESS");

        jLabel4.setText("GENDER");

        jLabel5.setText("PHONENO");

        tfpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfpinKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpinKeyTyped(evt);
            }
        });

        tfphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfphonenoActionPerformed(evt);
            }
        });
        tfphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfphonenoKeyPressed(evt);
            }
        });

        MaleRadioButton1.setText("Male");
        MaleRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButton1ActionPerformed(evt);
            }
        });

        femaleRadioButton1.setText("FEMALE");
        femaleRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButton1ActionPerformed(evt);
            }
        });

        CREATEBUTTON.setText("CREATE");
        CREATEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBUTTONActionPerformed(evt);
            }
        });

        jLabel7.setText("BODYTEMPERATURE");

        jLabel8.setText("SYMPTOMS");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "FEVER", "COLD", "HEADACHE", "BODYACHE", "ACNE", "DIARREHA" }));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("ENTER PATIENTS DETAILS");

        jLabel10.setText("BLOOD PRESSURE");

        jLabel11.setText("AGE");

        tfage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfageActionPerformed(evt);
            }
        });

        jLabel15.setText("RESPIRATIONRATE");

        javax.swing.GroupLayout firstpageLayout = new javax.swing.GroupLayout(firstpage);
        firstpage.setLayout(firstpageLayout);
        firstpageLayout.setHorizontalGroup(
            firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpageLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(firstpageLayout.createSequentialGroup()
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(99, 99, 99)
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(firstpageLayout.createSequentialGroup()
                                    .addComponent(MaleRadioButton1)
                                    .addGap(31, 31, 31)
                                    .addComponent(femaleRadioButton1))
                                .addComponent(jLabel9)
                                .addComponent(tfname, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(tfadd)
                                .addComponent(tfpin)))
                        .addComponent(CREATEBUTTON)
                        .addGroup(firstpageLayout.createSequentialGroup()
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(34, 34, 34)
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfphoneno)
                                .addComponent(tfbodytemp)
                                .addGroup(firstpageLayout.createSequentialGroup()
                                    .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfage, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfbloodpressure, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 251, Short.MAX_VALUE)
                                        .addComponent(tfrespirationrate))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(1150, Short.MAX_VALUE))
        );
        firstpageLayout.setVerticalGroup(
            firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaleRadioButton1)
                            .addComponent(femaleRadioButton1))))
                .addGap(18, 18, 18)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfbodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfrespirationrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(CREATEBUTTON)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        Parent.add(firstpage, "card2");

        secondpage.setBackground(new java.awt.Color(51, 255, 0));

        jLabel13.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel13.setText("VIEW/UPDATE PATIENTS DETAILS");

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setText("SEARCH");

        tfsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearchActionPerformed(evt);
            }
        });
        tfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearchKeyReleased(evt);
            }
        });

        UPDATEB1.setText("UPDATE");
        UPDATEB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEB1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 51, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "PINCODE", "GENDER", "PHONENO", "BODYTEMP", "SYMPTOMS", "BP", "AGE", "RESPIRATIONRATE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LOGOUTB.setText("LOGOUT");
        LOGOUTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secondpageLayout = new javax.swing.GroupLayout(secondpage);
        secondpage.setLayout(secondpageLayout);
        secondpageLayout.setHorizontalGroup(
            secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondpageLayout.createSequentialGroup()
                .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondpageLayout.createSequentialGroup()
                        .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(secondpageLayout.createSequentialGroup()
                                .addGap(598, 598, 598)
                                .addComponent(UPDATEB1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LOGOUTB))
                            .addGroup(secondpageLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel14)))
                        .addGap(27, 27, 27)
                        .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(secondpageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(603, Short.MAX_VALUE))
        );
        secondpageLayout.setVerticalGroup(
            secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UPDATEB1)
                    .addComponent(LOGOUTB))
                .addGap(384, 384, 384))
        );

        Parent.add(secondpage, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfageActionPerformed

    private void UPDATEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEBActionPerformed
        Parent.removeAll();
        Parent.add(secondpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_UPDATEBActionPerformed

    private void CREATEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBActionPerformed
        Parent.removeAll();
        Parent.add(firstpage);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_CREATEBActionPerformed

    private void CREATEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBUTTONActionPerformed
       if(tfname.getText().equals("")||tfadd.getText().equals("")||tfpin.getText().equals("")||tfphoneno.getText().equals("")||tfbodytemp.getText().equals("")||tfbloodpressure.getText().equals("")||jComboBox1. getSelectedItem().equals("")||tfage.getText().equals("")||tfrespirationrate.getText().equals(""))
       {
         JOptionPane.showMessageDialog(this,"Please Enter All Details");
    }//GEN-LAST:event_CREATEBUTTONActionPerformed
else
       {
           
           String data[]={tfname.getText(),tfadd.getText(),tfpin.getText(),MaleRadioButton1.getText(),tfphoneno.getText(),tfbodytemp.getText(),jComboBox1.getSelectedItem().toString(),tfbloodpressure.getText(),tfage.getText(),tfrespirationrate.getText()};
             DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                tb1Model.addRow(data);
                JOptionPane.showMessageDialog(this,"Add Data Successfully!");
                tfname.setText("");
                tfadd.setText("");
                tfpin.setText("");
                tfphoneno.setText("");
                tfbodytemp.setText("");
                jComboBox1. setSelectedItem("");
                tfbloodpressure.setText("");
                tfage.setText("");
                tfrespirationrate.setText("");
               

                
    }
       }
    
    private void tfsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearchKeyReleased
        DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
        jTable1.getModel();
        TableRowSorter <DefaultTableModel> tb = new TableRowSorter <DefaultTableModel>(tableModel);
        jTable1.setRowSorter(tb);
        tb.setRowFilter(RowFilter.regexFilter(tfsearch.getText()));   
    }//GEN-LAST:event_tfsearchKeyReleased

    private void UPDATEB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEB1ActionPerformed
       DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1)
        {
            String name=tfname.getText();
            String address=tfadd.getText();
             String pincode=tfpin.getText();
              String phno=tfphoneno.getText();
                 String bt=tfbodytemp.getText();
                String bp=tfbloodpressure.getText();
                 String age=tfage.getText();
                 String RespirationRate=tfrespirationrate.getText();
          JOptionPane.showMessageDialog(this,"Updated Successfully");
        }
        else{
            if(jTable1.getRowCount()==0)
            {
               JOptionPane.showMessageDialog(this,"Table is Empty"); 
            }
            else{
                JOptionPane.showMessageDialog(this,"Please select a single row for updation"); 
            }
        }      
    }//GEN-LAST:event_UPDATEB1ActionPerformed
 
    private void tfsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsearchActionPerformed

    private void LOGOUTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTBActionPerformed
           Loginpage p=new Loginpage();
     p.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_LOGOUTBActionPerformed

    private void tfphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfphonenoActionPerformed
        
    }//GEN-LAST:event_tfphonenoActionPerformed

    private void tfphonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfphonenoKeyPressed
       String MOB = tfphoneno.getText();
        if(MOB.matches("^[1-9]{1}[0-9]{9}$") ){
            tfphoneno.setBackground(java.awt.Color.green);
            tfphoneno.setEditable(true);
        }
        else{
         tfphoneno.setBackground(java.awt.Color.red);
         
        }
    }//GEN-LAST:event_tfphonenoKeyPressed

    private void tfpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpinKeyPressed
        
    }//GEN-LAST:event_tfpinKeyPressed

    private void tfpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpinKeyTyped
        char c= evt.getKeyChar();
        if(!(Character.isDigit(c)))
        {
          evt.consume();
        }
    }//GEN-LAST:event_tfpinKeyTyped

    private void MaleRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButton1ActionPerformed
        
        String Gender;
        Gender="MALE";
    }//GEN-LAST:event_MaleRadioButton1ActionPerformed

    private void femaleRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButton1ActionPerformed
       String Gender;
        Gender="FEMALE";
    }//GEN-LAST:event_femaleRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       ArrayList<Doctor>Doctorlist =new ArrayList<>();
      DefaultTableModel tableModel;


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctoraccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREATEB;
    private javax.swing.JButton CREATEBUTTON;
    private javax.swing.JButton LOGOUTB;
    private javax.swing.JRadioButton MaleRadioButton1;
    private javax.swing.JPanel Parent;
    private javax.swing.JButton UPDATEB;
    private javax.swing.JButton UPDATEB1;
    private javax.swing.JRadioButton femaleRadioButton1;
    private javax.swing.JPanel firstpage;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel secondpage;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfage;
    private javax.swing.JTextField tfbloodpressure;
    private javax.swing.JTextField tfbodytemp;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfphoneno;
    private javax.swing.JTextField tfpin;
    private javax.swing.JTextField tfrespirationrate;
    private javax.swing.JTextField tfsearch;
    // End of variables declaration//GEN-END:variables
}
