/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import java.util.regex.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import com.mycompany.hms.Doctor;
import java.util.ArrayList;
/**

/**
 *
 * @author HP
 */
public class Hospitaladmin1 extends javax.swing.JFrame {

    /**
     * Creates new form Hospitaladmin1
     */
    public Hospitaladmin1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstpage1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfname1 = new javax.swing.JTextField();
        tfadd1 = new javax.swing.JTextField();
        tfpin1 = new javax.swing.JTextField();
        tfphoneno1 = new javax.swing.JTextField();
        CREATEBUTTON1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxDepartment = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        tfdoctorid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxexperience = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfsearch = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        UPDATEB1 = new javax.swing.JButton();
        LOGOUTB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstpage1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel4.setText("NAME");

        jLabel7.setText("PINCODE");

        jLabel8.setText("ADDRESS");

        jLabel11.setText("PHONENO");

        CREATEBUTTON1.setText("CREATE");
        CREATEBUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEBUTTON1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel15.setText("ENTER DOCTOR DETAILS");

        jLabel13.setText("DEPARTMENT");

        jComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "DENTAL", "MICROBIOLOGY", "CARDIOLOGY", "GYNAECOLOGY", "NEUROLOGY", " " }));

        jLabel14.setText("DOCTOR ID");

        jLabel18.setText("EXPERIENCE");

        jComboBoxexperience.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select input", "0-5", "5-10", "10-15", "15-25", "25-35" }));
        jComboBoxexperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxexperienceActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "PINCODE", "EXPERIENCE", "PHONENUMBER", "DEPARTMENT", "DOCTORID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tfsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearchActionPerformed(evt);
            }
        });
        tfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsearchKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel16.setText("SEARCH");

        UPDATEB1.setText("UPDATE");
        UPDATEB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEB1ActionPerformed(evt);
            }
        });

        LOGOUTB.setText("LOGOUT");
        LOGOUTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstpage1Layout = new javax.swing.GroupLayout(firstpage1);
        firstpage1.setLayout(firstpage1Layout);
        firstpage1Layout.setHorizontalGroup(
            firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpage1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(38, 38, 38)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CREATEBUTTON1)
                            .addGroup(firstpage1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel15)))
                        .addGap(1167, 1167, 1167))
                    .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstpage1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(firstpage1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(firstpage1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(tfdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxexperience, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfpin1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfadd1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfname1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfphoneno1))
                            .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(firstpage1Layout.createSequentialGroup()
                                    .addGap(261, 261, 261)
                                    .addComponent(jLabel16)
                                    .addGap(53, 53, 53)
                                    .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(firstpage1Layout.createSequentialGroup()
                                    .addGap(116, 116, 116)
                                    .addComponent(UPDATEB1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(139, 139, 139)
                                    .addComponent(LOGOUTB))
                                .addGroup(firstpage1Layout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(680, 680, 680)))))
        );
        firstpage1Layout.setVerticalGroup(
            firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstpage1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addComponent(tfadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfpin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jComboBoxexperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstpage1Layout.createSequentialGroup()
                        .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfphoneno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UPDATEB1)
                        .addComponent(LOGOUTB)))
                .addGap(21, 21, 21)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(tfdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(CREATEBUTTON1)
                .addGap(341, 341, 341))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(firstpage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstpage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CREATEBUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEBUTTON1ActionPerformed
        if(tfname1.getText().equals("")||tfadd1.getText().equals("")||tfpin1.getText().equals("")||jComboBoxexperience. getSelectedItem().equals("")||tfphoneno1.getText().equals("")||jComboBoxDepartment. getSelectedItem().equals("")||tfdoctorid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter All Details");
    }//GEN-LAST:event_CREATEBUTTON1ActionPerformed
    else
       {
           String data[]={tfname1.getText(),tfadd1.getText(),tfpin1.getText(),tfphoneno1.getText(),jComboBoxDepartment.getSelectedItem().toString(),jComboBoxexperience. getSelectedItem().toString()};
              DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                tb1Model.addRow(data); 
                JOptionPane.showMessageDialog(this,"Appointment Booked  Successfully!");
                tfname1.setText("");
                tfadd1.setText("");
                tfpin1.setText("");
                tfphoneno1.setText("");
                tfdoctorid.setText("");
                 jComboBoxDepartment. setSelectedItem("");
                  jComboBoxexperience. setSelectedItem("");
                
       }
    }
    
    private void jComboBoxexperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxexperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxexperienceActionPerformed

    private void tfsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsearchActionPerformed

    private void tfsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearchKeyReleased
        DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
        jTable1.getModel();
        TableRowSorter <DefaultTableModel> tb = new TableRowSorter <DefaultTableModel>(tableModel);
        jTable1.setRowSorter(tb);
        tb.setRowFilter(RowFilter.regexFilter(tfsearch.getText()));
    }//GEN-LAST:event_tfsearchKeyReleased

    private void UPDATEB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEB1ActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1)
        {
            String name=tfname1.getText();
            String address=tfadd1.getText();
            String pincode=tfpin1.getText();
            String phno=tfphoneno1.getText();
             String doctor=tfdoctorid.getText();
            
            JOptionPane.showMessageDialog(this,"Updated Successfully");
        }
        else{
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                JOptionPane.showMessageDialog(this,"Please select a single row for updation");
            }
        }
    }//GEN-LAST:event_UPDATEB1ActionPerformed

    private void LOGOUTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTBActionPerformed
        Loginpage p=new Loginpage();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospitaladmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospitaladmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospitaladmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospitaladmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospitaladmin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREATEBUTTON1;
    private javax.swing.JButton LOGOUTB;
    private javax.swing.JButton UPDATEB1;
    private javax.swing.JPanel firstpage1;
    private javax.swing.JComboBox<String> jComboBoxDepartment;
    private javax.swing.JComboBox<String> jComboBoxexperience;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfadd1;
    private javax.swing.JTextField tfdoctorid;
    private javax.swing.JTextField tfname1;
    private javax.swing.JTextField tfphoneno1;
    private javax.swing.JTextField tfpin1;
    private javax.swing.JTextField tfsearch;
    // End of variables declaration//GEN-END:variables
}
